name: edtechapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  google_fonts: ^5.0.1
  snackbar: ^1.0.2
  stacked: ^3.4.1
  stacked_services: ^1.2.0
  bottom_nav_bar: ^1.0.3
  bottom_navy_bar: ^6.0.0
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.0
  dartz: ^0.10.1
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  youtube_player_flutter: ^8.1.2
  image_picker: ^1.0.1
  firebase_storage: ^11.2.5
  flutter_login_facebook: ^1.8.0
  flutter_facebook_auth: ^6.0.0
  google_sign_in: ^6.1.4


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/Rubik/Rubik-VariableFont_wght.ttf
