// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhs0f9YmHm92nkbqPN0vW2TFxout8MafQ',
    appId: '1:273139588544:web:cb446c5d2b1a2fa3467c25',
    messagingSenderId: '273139588544',
    projectId: 'edtech-mobileapp',
    authDomain: 'edtech-mobileapp.firebaseapp.com',
    storageBucket: 'edtech-mobileapp.appspot.com',
    measurementId: 'G-N039LM49MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkH9shYG__EK7-FUwzFatKQX8SvG10IE0',
    appId: '1:273139588544:android:952ccd5497431fb5467c25',
    messagingSenderId: '273139588544',
    projectId: 'edtech-mobileapp',
    storageBucket: 'edtech-mobileapp.appspot.com',
  );
}
