// Mocks generated by Mockito 5.4.2 from annotations
// in edtechapp/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i10;

import 'package:cloud_firestore/cloud_firestore.dart' as _i3;
import 'package:dartz/dartz.dart' as _i6;
import 'package:edtechapp/exception/app_exception.dart' as _i17;
import 'package:edtechapp/model/course.dart' as _i5;
import 'package:edtechapp/model/user.dart' as _i4;
import 'package:edtechapp/services/authentication_service.dart' as _i16;
import 'package:edtechapp/services/course_impl_service.dart' as _i15;
import 'package:edtechapp/services/repository_impl_service.dart' as _i12;
import 'package:edtechapp/services/repository_service.dart' as _i11;
import 'package:edtechapp/services/share_impl_service.dart' as _i14;
import 'package:edtechapp/services/shared_pref_service_service.dart' as _i18;
import 'package:edtechapp/services/shared_service.dart' as _i13;
import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:flutter/material.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stacked_services/stacked_services.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseAuth_0 extends _i1.SmartFake implements _i2.FirebaseAuth {
  _FakeFirebaseAuth_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseFirestore_1 extends _i1.SmartFake
    implements _i3.FirebaseFirestore {
  _FakeFirebaseFirestore_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_2 extends _i1.SmartFake implements _i2.User {
  _FakeUser_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_3 extends _i1.SmartFake implements _i4.User {
  _FakeUser_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCourse_4 extends _i1.SmartFake implements _i5.Course {
  _FakeCourse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_5<L, R> extends _i1.SmartFake implements _i6.Either<L, R> {
  _FakeEither_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i7.NavigationService {
  @override
  String get previousRoute => (super.noSuchMethod(
        Invocation.getter(#previousRoute),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get currentRoute => (super.noSuchMethod(
        Invocation.getter(#currentRoute),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i8.GlobalKey<_i8.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #nestedNavigationKey,
          [index],
        ),
        returnValueForMissingStub: null,
      ) as _i8.GlobalKey<_i8.NavigatorState>?);
  @override
  void config({
    bool? enableLog,
    bool? defaultPopGesture,
    bool? defaultOpaqueRoute,
    Duration? defaultDurationTransition,
    bool? defaultGlobalState,
    _i7.Transition? defaultTransitionStyle,
    String? defaultTransition,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #config,
          [],
          {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransitionStyle: defaultTransitionStyle,
            #defaultTransition: defaultTransition,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i9.Future<T?>? navigateWithTransition<T>(
    _i8.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i8.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i7.Transition? transitionClass,
    _i7.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);
  @override
  _i9.Future<T?>? replaceWithTransition<T>(
    _i8.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i8.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i7.Transition? transitionClass,
    _i7.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);
  @override
  bool back<T>({
    dynamic result,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {
            #result: result,
            #id: id,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void popUntil(
    _i8.RoutePredicate? predicate, {
    int? id,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void popRepeated(int? popTimes) => super.noSuchMethod(
        Invocation.method(
          #popRepeated,
          [popTimes],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i9.Future<T?>? navigateTo<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i8.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);
  @override
  _i9.Future<T?>? navigateToView<T>(
    _i8.Widget? view, {
    dynamic arguments,
    int? id,
    bool? opaque,
    _i8.Curve? curve,
    Duration? duration,
    bool? fullscreenDialog = false,
    bool? popGesture,
    bool? preventDuplicates = true,
    _i7.Transition? transition,
    _i7.Transition? transitionStyle,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToView,
          [view],
          {
            #arguments: arguments,
            #id: id,
            #opaque: opaque,
            #curve: curve,
            #duration: duration,
            #fullscreenDialog: fullscreenDialog,
            #popGesture: popGesture,
            #preventDuplicates: preventDuplicates,
            #transition: transition,
            #transitionStyle: transitionStyle,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);
  @override
  _i9.Future<T?>? replaceWith<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i8.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);
  @override
  _i9.Future<T?>? clearStackAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);
  @override
  _i9.Future<T?>? clearStackAndShowView<T>(
    _i8.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);
  @override
  _i9.Future<T?>? clearTillFirstAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);
  @override
  _i9.Future<T?>? clearTillFirstAndShowView<T>(
    _i8.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);
  @override
  _i9.Future<T?>? pushNamedAndRemoveUntil<T>(
    String? routeName, {
    _i8.RoutePredicate? predicate,
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamedAndRemoveUntil,
          [routeName],
          {
            #predicate: predicate,
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock
    implements _i7.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i7.SheetBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #setCustomSheetBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i9.Future<_i7.SheetResponse<dynamic>?> showBottomSheet({
    required String? title,
    String? description,
    String? confirmButtonTitle = r'Ok',
    String? cancelButtonTitle,
    bool? enableDrag = true,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [],
          {
            #title: title,
            #description: description,
            #confirmButtonTitle: confirmButtonTitle,
            #cancelButtonTitle: cancelButtonTitle,
            #enableDrag: enableDrag,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i9.Future<_i7.SheetResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i9.Future<_i7.SheetResponse<dynamic>?>.value(),
      ) as _i9.Future<_i7.SheetResponse<dynamic>?>);
  @override
  _i9.Future<_i7.SheetResponse<T>?> showCustomSheet<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i10.Color? barrierColor = const _i10.Color(2315255808),
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    String? barrierLabel = r'',
    dynamic customData,
    R? data,
    bool? enableDrag = true,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomSheet,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
            #enableDrag: enableDrag,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i9.Future<_i7.SheetResponse<T>?>.value(),
        returnValueForMissingStub: _i9.Future<_i7.SheetResponse<T>?>.value(),
      ) as _i9.Future<_i7.SheetResponse<T>?>);
  @override
  void completeSheet(_i7.SheetResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeSheet,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i7.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i7.DialogBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i8.Widget Function(
      _i8.BuildContext,
      _i7.DialogRequest<dynamic>,
      dynamic Function(_i7.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i9.Future<_i7.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i10.Color? cancelTitleColor,
    String? buttonTitle = r'Ok',
    _i10.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i7.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i9.Future<_i7.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i9.Future<_i7.DialogResponse<dynamic>?>.value(),
      ) as _i9.Future<_i7.DialogResponse<dynamic>?>);
  @override
  _i9.Future<_i7.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i10.Color? barrierColor = const _i10.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = r'',
    bool? useSafeArea = true,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #useSafeArea: useSafeArea,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i9.Future<_i7.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i9.Future<_i7.DialogResponse<T>?>.value(),
      ) as _i9.Future<_i7.DialogResponse<T>?>);
  @override
  _i9.Future<_i7.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = r'Cancel',
    _i10.Color? cancelTitleColor,
    String? confirmationTitle = r'Ok',
    _i10.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i7.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #confirmationTitle: confirmationTitle,
            #confirmationTitleColor: confirmationTitleColor,
            #barrierDismissible: barrierDismissible,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i9.Future<_i7.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i9.Future<_i7.DialogResponse<dynamic>?>.value(),
      ) as _i9.Future<_i7.DialogResponse<dynamic>?>);
  @override
  void completeDialog(_i7.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RepositoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRepositoryService extends _i1.Mock implements _i11.RepositoryService {
  @override
  _i9.Future<List<_i5.Course>> getCourse() => (super.noSuchMethod(
        Invocation.method(
          #getCourse,
          [],
        ),
        returnValue: _i9.Future<List<_i5.Course>>.value(<_i5.Course>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i5.Course>>.value(<_i5.Course>[]),
      ) as _i9.Future<List<_i5.Course>>);
}

/// A class which mocks [RepositoryImplService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRepositoryImplService extends _i1.Mock
    implements _i12.RepositoryImplService {
  @override
  _i2.FirebaseAuth get auth0 => (super.noSuchMethod(
        Invocation.getter(#auth0),
        returnValue: _FakeFirebaseAuth_0(
          this,
          Invocation.getter(#auth0),
        ),
        returnValueForMissingStub: _FakeFirebaseAuth_0(
          this,
          Invocation.getter(#auth0),
        ),
      ) as _i2.FirebaseAuth);
  @override
  _i3.FirebaseFirestore get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeFirebaseFirestore_1(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_1(
          this,
          Invocation.getter(#db),
        ),
      ) as _i3.FirebaseFirestore);
  @override
  _i2.User get userName => (super.noSuchMethod(
        Invocation.getter(#userName),
        returnValue: _FakeUser_2(
          this,
          Invocation.getter(#userName),
        ),
        returnValueForMissingStub: _FakeUser_2(
          this,
          Invocation.getter(#userName),
        ),
      ) as _i2.User);
  @override
  _i9.Future<String?> forgetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [email],
        ),
        returnValue: _i9.Future<String?>.value(),
        returnValueForMissingStub: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);
  @override
  _i9.Future<List<_i5.Course>> getCourse() => (super.noSuchMethod(
        Invocation.method(
          #getCourse,
          [],
        ),
        returnValue: _i9.Future<List<_i5.Course>>.value(<_i5.Course>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i5.Course>>.value(<_i5.Course>[]),
      ) as _i9.Future<List<_i5.Course>>);
}

/// A class which mocks [SharedService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedService extends _i1.Mock implements _i13.SharedService {
  @override
  _i9.Future<void> setUser(
    String? key,
    _i4.User? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUser,
          [
            key,
            user,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<_i4.User> getUser(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [key],
        ),
        returnValue: _i9.Future<_i4.User>.value(_FakeUser_3(
          this,
          Invocation.method(
            #getUser,
            [key],
          ),
        )),
        returnValueForMissingStub: _i9.Future<_i4.User>.value(_FakeUser_3(
          this,
          Invocation.method(
            #getUser,
            [key],
          ),
        )),
      ) as _i9.Future<_i4.User>);
  @override
  _i9.Future<void> setCourse(
    String? key,
    _i5.Course? course,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCourse,
          [
            key,
            course,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<_i5.Course> getCourse(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getCourse,
          [key],
        ),
        returnValue: _i9.Future<_i5.Course>.value(_FakeCourse_4(
          this,
          Invocation.method(
            #getCourse,
            [key],
          ),
        )),
        returnValueForMissingStub: _i9.Future<_i5.Course>.value(_FakeCourse_4(
          this,
          Invocation.method(
            #getCourse,
            [key],
          ),
        )),
      ) as _i9.Future<_i5.Course>);
}

/// A class which mocks [ShareImplService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShareImplService extends _i1.Mock implements _i14.ShareImplService {
  @override
  _i9.Future<_i4.User> getUser(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [key],
        ),
        returnValue: _i9.Future<_i4.User>.value(_FakeUser_3(
          this,
          Invocation.method(
            #getUser,
            [key],
          ),
        )),
        returnValueForMissingStub: _i9.Future<_i4.User>.value(_FakeUser_3(
          this,
          Invocation.method(
            #getUser,
            [key],
          ),
        )),
      ) as _i9.Future<_i4.User>);
  @override
  _i9.Future<void> setUser(
    String? key,
    _i4.User? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUser,
          [
            key,
            user,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<_i5.Course> getCourse(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getCourse,
          [key],
        ),
        returnValue: _i9.Future<_i5.Course>.value(_FakeCourse_4(
          this,
          Invocation.method(
            #getCourse,
            [key],
          ),
        )),
        returnValueForMissingStub: _i9.Future<_i5.Course>.value(_FakeCourse_4(
          this,
          Invocation.method(
            #getCourse,
            [key],
          ),
        )),
      ) as _i9.Future<_i5.Course>);
  @override
  _i9.Future<void> setCourse(
    String? key,
    _i5.Course? course,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCourse,
          [
            key,
            course,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [CourseImplService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseImplService extends _i1.Mock implements _i15.CourseImplService {
  @override
  _i9.Future<List<_i5.Course>?> course() => (super.noSuchMethod(
        Invocation.method(
          #course,
          [],
        ),
        returnValue: _i9.Future<List<_i5.Course>?>.value(),
        returnValueForMissingStub: _i9.Future<List<_i5.Course>?>.value(),
      ) as _i9.Future<List<_i5.Course>?>);
}

/// A class which mocks [AuthenticationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationService extends _i1.Mock
    implements _i16.AuthenticationService {
  @override
  _i9.Future<_i6.Either<_i17.AppException, _i6.None<dynamic>>> signup(
    String? name,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signup,
          [
            name,
            email,
            password,
          ],
        ),
        returnValue:
            _i9.Future<_i6.Either<_i17.AppException, _i6.None<dynamic>>>.value(
                _FakeEither_5<_i17.AppException, _i6.None<dynamic>>(
          this,
          Invocation.method(
            #signup,
            [
              name,
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Either<_i17.AppException, _i6.None<dynamic>>>.value(
                _FakeEither_5<_i17.AppException, _i6.None<dynamic>>(
          this,
          Invocation.method(
            #signup,
            [
              name,
              email,
              password,
            ],
          ),
        )),
      ) as _i9.Future<_i6.Either<_i17.AppException, _i6.None<dynamic>>>);
  @override
  _i9.Future<_i6.Either<_i17.AppException, _i4.User>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i9.Future<_i6.Either<_i17.AppException, _i4.User>>.value(
            _FakeEither_5<_i17.AppException, _i4.User>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Either<_i17.AppException, _i4.User>>.value(
                _FakeEither_5<_i17.AppException, _i4.User>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i9.Future<_i6.Either<_i17.AppException, _i4.User>>);
  @override
  _i9.Future<_i6.Either<_i17.AppException, _i6.None<dynamic>>> forgetPassword(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [email],
        ),
        returnValue:
            _i9.Future<_i6.Either<_i17.AppException, _i6.None<dynamic>>>.value(
                _FakeEither_5<_i17.AppException, _i6.None<dynamic>>(
          this,
          Invocation.method(
            #forgetPassword,
            [email],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Either<_i17.AppException, _i6.None<dynamic>>>.value(
                _FakeEither_5<_i17.AppException, _i6.None<dynamic>>(
          this,
          Invocation.method(
            #forgetPassword,
            [email],
          ),
        )),
      ) as _i9.Future<_i6.Either<_i17.AppException, _i6.None<dynamic>>>);
}

/// A class which mocks [SharedPrefServiceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPrefServiceService extends _i1.Mock
    implements _i18.SharedPrefServiceService {
  @override
  _i9.Future<void> saveUser(_i4.User? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}
